name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ios:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # (Optional) Set correct Xcode version
    - name: Select Xcode 15.2
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app

    # (Optional) Install xcbeautify for readable logs
    - name: Install xcbeautify
      run: brew install xcbeautify

    # Run tests using the MenuVision scheme and test plan
    - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
      working-directory: frontend/MenuVision
      run: |
        xcodebuild test \
          -project MenuVision.xcodeproj \
          -scheme MenuVision \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
        | xcbeautify && exit ${PIPESTATUS[0]}
