name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, feature/* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 15.2
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Run Tests
        working-directory: frontend/MenuVision
        run: |
          xcodebuild test \
            -project MenuVision.xcodeproj \
            -scheme MenuVision \
            -resultBundlePath TestResults \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=16.0"

      - uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: frontend/MenuVision/TestResults.xcresult