name: iOS Tests (Unit, Integration, System)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-13

    defaults:
      run:
        working-directory: frontend/MenuVision

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Run All Tests with Test Plan
      run: |
        xcodebuild test \
          -project MenuVision.xcodeproj \
          -scheme MenuVision \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -testPlan TestPlan \
        | xcbeautify --report junit --junit-report-filename TestPlanReport.xml

    - name: Upload Test Plan Report
      uses: actions/upload-artifact@v4
      with:
        name: TestPlan-Test-Report
        path: TestPlanReport.xml

    - name: Publish Combined Test Summary
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: All Test Results
        path: '**/*.xml'
        reporter: java-junit
